---
version: '3'
services:
  db:
    image: docker.io/postgres:bullseye
    container_name: postgres
    # need to enable WAL logical replication at startup
    command: postgres -c wal_level=logical
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"

  database-setup:
    build:
      context: ./database-setup
      no_cache: true
    image: database-setup
    container_name: database-setup
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USER_PASSWORD: "postgres"
      POSTGRES_ADMIN_PASSWORD: "postgres"

  debezium-server:
    image: quay.io/debezium/server:2.3
    container_name: debezium-server
    restart: always
    healthcheck:
      test: curl http://debezium-server:8080/q/health || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      database-setup:
        condition: service_completed_successfully
      memphis-rest-gateway:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./debezium-conf:/debezium/conf:ro

  todo-generator:
    build:
      context: ./todo-generator
      no_cache: true
    image: todo-generator
    container_name: todo-generator
    restart: always
    depends_on:
      db:
        condition: service_healthy
      debezium-server:
        condition: service_healthy
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USERNAME: "todo_service"
      POSTGRES_PASSWORD: "postgres"

  printing-consumer:
    build:
      context: ./printing-consumer
      no_cache: true
    image: printing-consumer
    container_name: printing-consumer
    restart: always
    depends_on:
      memphis:
        condition: service_healthy
    environment:
      MEMPHIS_HOST: "memphis"
      MEMPHIS_USERNAME: "todocdcservice"
      MEMPHIS_PASSWORD: "todocdcservice"
      MEMPHIS_STATION: "todo-cdc-events"

  memphis-metadata:
    image: memphisos/memphis-metadata:15-docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memphis -p 5005"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5005:5005"
    environment:
      - POSTGRESQL_USERNAME=memphis
      - POSTGRESQL_PASSWORD=memphis
      - POSTGRESQL_DATABASE=memphis
      - POSTGRESQL_PORT_NUMBER=5005

  memphis:
    image: "memphisos/memphis:latest"
    depends_on:
      memphis-metadata:
        condition: service_healthy
    healthcheck:
      test: wget http://memphis:9000 --spider || exit 1
      interval: 10s
      retries: 30
      start_period: 5s
    restart: on-failure
    ports:
      - "9000:9000"
      - "6666:6666"
      - "7770:7770"
    environment:
      - ROOT_PASSWORD=memphis
      - DOCKER_ENV=true
      - ANALYTICS=true
      - USER_PASS_BASED_AUTH=true
      - CONNECTION_TOKEN=memphis
      - METADATA_DB_HOST=memphis-metadata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  memphis-rest-gateway:
    image: "memphisos/memphis-rest-gateway:latest"
    depends_on:
      memphis:
        condition: service_healthy
    restart: on-failure
    ports:
      - "4444:4444"
    environment:
      - JWT_SECRET=JWT_TEST_PURPOSE
      - REFRESH_JWT_SECRET=REFRESH_JWT_TEST_PURPOSE
      - USER_PASS_BASED_AUTH=true
      - CONNECTION_TOKEN=memphis
      - ROOT_USER=root
      - ROOT_PASSWORD=memphis
      - MEMPHIS_HOST=memphis
      - HTTP_PORT=4444
