---
version: '3'
services:
  memphis-metadata:
    image: memphisos/memphis-metadata:15-docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memphis -p 5005"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5005:5005"
    environment:
      - POSTGRESQL_USERNAME=memphis
      - POSTGRESQL_PASSWORD=memphis
      - POSTGRESQL_DATABASE=memphis
      - POSTGRESQL_PORT_NUMBER=5005

  memphis:
    image: "memphisos/memphis:latest"
    depends_on:
      memphis-metadata:
        condition: service_healthy
    healthcheck:
      test: wget http://memphis:9000 --spider || exit 1
      interval: 10s
      retries: 30
      start_period: 5s
    restart: on-failure
    ports:
      - "9000:9000"
      - "6666:6666"
      - "7770:7770"
    environment:
      - ROOT_PASSWORD=memphis
      - DOCKER_ENV=true
      - ANALYTICS=true
      - USER_PASS_BASED_AUTH=true
      - CONNECTION_TOKEN=memphis
      - METADATA_DB_HOST=memphis-metadata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  input-data:
    build:
      context: ./input_data
      no_cache: true
    restart: "no"
    depends_on:
      memphis:
        condition: service_healthy
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USERNAME: "todo_service"
      POSTGRES_PASSWORD: "postgres"
